services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://movedin:movedin@postgres:5432/movedin
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=movedin
      - POSTGRES_USER=movedin
      - POSTGRES_PASSWORD=movedin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 