# MovedIn 3.0 - Production Docker Compose
# Optimized for GitHub and Render deployment

services:
  # MovedIn 3.0 Backend API
  movedin-backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: movedin-backend-prod
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./movedin.db
      - SMTP_SERVER=smtp.office365.com
      - SMTP_PORT=587
      - SMTP_USERNAME=support@movedin.com
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
      - SECRET_KEY=${SECRET_KEY:-movedin3-smart-secure-key-2025}
      - DEBUG=false
      - PORT=8000
    volumes:
      - movedin-db:/app/movedin.db
      - movedin-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - movedin-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # MovedIn 3.0 Frontend
  movedin-frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: movedin-frontend-prod
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      - VITE_ENVIRONMENT=production
      - PORT=3000
    depends_on:
      movedin-backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - movedin-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  movedin-network:
    driver: bridge

volumes:
  movedin-db:
    driver: local
  movedin-logs:
    driver: local
