# MovedIn 2.0 Blueprint Configuration
# Based on official Render Blueprint specification

# PostgreSQL databases
databases:
  - name: movedin-database
    databaseName: movedin
    user: movedin
    plan: basic-256mb

# Services (non-PostgreSQL)
services:
  # Redis Key Value instance
  - type: keyvalue
    name: movedin-redis
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

  # Backend API (Docker-based web service)
  - type: web
    name: movedin-backend
    runtime: docker
    plan: starter
    dockerfilePath: backend/Dockerfile
    build:
      context: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movedin-database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: movedin-redis
          property: connectionString
      - key: DEBUG
        value: "false"
      - key: ZOHO_CLIENT_ID
        sync: false
      - key: ZOHO_CLIENT_SECRET
        sync: false
      - key: ZOHO_REDIRECT_URI
        value: https://movedin-backend.onrender.com/api/zoho/callback
      - key: ZOHO_AUTH_URL
        value: https://accounts.zoho.com/oauth/v2/auth
      - key: ZOHO_TOKEN_URL
        value: https://accounts.zoho.com/oauth/v2/token
      - key: ZOHO_CRM_API_URL
        value: https://www.zohoapis.com/crm/v3

  # Frontend (Static site)
  - type: web
    name: movedin-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://movedin-backend.onrender.com
      - key: VITE_MAPBOX_ACCESS_TOKEN
        sync: false 