# MovedIn 3.0 - Render.com Configuration
# Direct Node.js deployment (matching existing setup)

services:
  # Backend API Service
  - type: web
    name: movedin-backend
    env: python
    buildCommand: pip install -r src/backend/requirements.txt
    startCommand: cd src/backend && python main.py
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: sqlite:///./movedin.db
      - key: SMTP_SERVER
        value: smtp.office365.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: support@movedin.com
      - key: SMTP_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: MAPBOX_ACCESS_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PORT
        value: 8000

  # Frontend Static Site
  - type: static
    name: movedin-frontend
    buildCommand: cd src/frontend && npm install && npm run build
    publishDirectory: src/frontend/dist
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: movedin-backend
          property: host
      - key: VITE_ENVIRONMENT
        value: production
